# Generated by Django 5.1.7 on 2025-03-25 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_description_listing_sold_listing_type_and_more'),
    ]

    operations = [
        migrations.RenameField('Listing', 'year_formed', 'year'),
    ]
